# Generated by Django 5.2 on 2025-06-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
