# Generated by Django 5.2 on 2025-06-24 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchPredictionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_timestamp", models.DateTimeField(auto_now_add=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("num_records", models.IntegerField(blank=True, null=True)),
                (
                    "model_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.ml_models",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Batch Prediction Runs",
                "db_table": "Batch_Prediction_Run",
            },
        ),
        migrations.AlterField(
            model_name="batch_cvd_risk_output",
            name="risk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.batchpredictionrun",
            ),
        ),
        migrations.DeleteModel(
            name="batch_CVD_Risk_Risk",
        ),
    ]
