# Generated by Django 5.2 on 2025-06-24 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_batchpredictionrun_alter_batch_cvd_risk_output_risk_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchPredictionResultDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_row_index", models.IntegerField()),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("systolic_bp", models.IntegerField()),
                ("diastolic_bp", models.IntegerField()),
                ("cholesterol", models.IntegerField()),
                ("glucose", models.IntegerField()),
                ("smoking", models.CharField(max_length=10)),
                ("alcohol", models.CharField(max_length=10)),
                ("physical_activity", models.IntegerField()),
                ("risk_score", models.DecimalField(decimal_places=4, max_digits=7)),
                ("risk_level", models.CharField(max_length=50)),
                (
                    "batch_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="accounts.batchpredictionrun",
                    ),
                ),
            ],
        ),
    ]
