# Generated by Django 5.2 on 2025-05-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_users_password"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="cvd_risk_questionnaire",
            name="dependencies",
        ),
        migrations.AlterField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cvd_risk_questionnaire",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, to="accounts.cvd_risk_questionnaire"
            ),
        ),
    ]
