# Generated by Django 5.1.7 on 2025-05-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_accountsquestionnaire_accountsresponse_accountsuser_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="batch_CVD_Risk_Features",
            fields=[
                ("feature_id", models.AutoField(primary_key=True, serialize=False)),
                ("feature_name", models.CharField(max_length=255)),
                ("feature_description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "batch_CVD_Risk_Features",
            },
        ),
        migrations.CreateModel(
            name="batch_CVD_Risk_Model_Features",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.batch_cvd_risk_features",
                    ),
                ),
            ],
            options={
                "db_table": "batch_CVD_Risk_Model_Features",
            },
        ),
        migrations.CreateModel(
            name="batch_CVD_Risk_Output",
            fields=[
                ("output_id", models.AutoField(primary_key=True, serialize=False)),
                ("plot_type", models.CharField(max_length=100)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "batch_CVD_Risk_Output",
            },
        ),
        migrations.CreateModel(
            name="batch_CVD_Risk_Risk",
            fields=[
                ("risk_id", models.AutoField(primary_key=True, serialize=False)),
                ("risk_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("prediction_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "batch_CVD_Risk_Risk",
            },
        ),
        migrations.CreateModel(
            name="CVD_risk_Clinician_Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "CVD_risk_Clinician_Patient",
            },
        ),
        migrations.CreateModel(
            name="CVD_risk_Patient_Outcomes",
            fields=[
                ("outcome_id", models.AutoField(primary_key=True, serialize=False)),
                ("outcome_description", models.TextField()),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "CVD_risk_Patient_Outcomes",
            },
        ),
        migrations.CreateModel(
            name="CVD_risk_Questionnaire",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_text", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "subcategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("question_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "CVD_risk_Questionnaire",
            },
        ),
        migrations.CreateModel(
            name="CVD_risk_QuestionResponseOptions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("option_text", models.TextField()),
                ("value_range_start", models.FloatField(blank=True, null=True)),
                ("value_range_end", models.FloatField(blank=True, null=True)),
                (
                    "option_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "CVD_risk_QuestionResponseOptions",
            },
        ),
        migrations.CreateModel(
            name="CVD_risk_Responses",
            fields=[
                ("response_id", models.AutoField(primary_key=True, serialize=False)),
                ("response_type", models.CharField(max_length=50)),
                ("numeric_response", models.FloatField(blank=True, null=True)),
                ("boolean_response", models.BooleanField(blank=True, null=True)),
                ("response_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "CVD_risk_Responses",
            },
        ),
        migrations.CreateModel(
            name="ML_Models",
            fields=[
                ("model_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=255)),
                ("model_type", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "ML_Models",
            },
        ),
        migrations.CreateModel(
            name="Risk_Stratification",
            fields=[
                (
                    "stratification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("risk_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("recommendation", models.TextField()),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.ml_models",
                    ),
                ),
            ],
            options={
                "db_table": "Risk_Stratification",
            },
        ),
        migrations.DeleteModel(
            name="AccountsQuestionnaire",
        ),
        migrations.DeleteModel(
            name="AccountsResponse",
        ),
        migrations.DeleteModel(
            name="AccountsUser",
        ),
        migrations.DeleteModel(
            name="AccountsUserGroups",
        ),
        migrations.DeleteModel(
            name="AccountsUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.RemoveField(
            model_name="clinicianpatient",
            name="clinician",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
        migrations.DeleteModel(
            name="MlModels",
        ),
        migrations.DeleteModel(
            name="PatientOutcomes",
        ),
        migrations.DeleteModel(
            name="Questionnaire",
        ),
        migrations.DeleteModel(
            name="Responses",
        ),
        migrations.DeleteModel(
            name="RiskStratification",
        ),
        migrations.AlterModelOptions(
            name="admins",
            options={},
        ),
        migrations.AlterModelOptions(
            name="clinicians",
            options={},
        ),
        migrations.AlterModelOptions(
            name="patients",
            options={},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={},
        ),
        migrations.AddField(
            model_name="batch_cvd_risk_risk",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.patients"
            ),
        ),
        migrations.AddField(
            model_name="batch_cvd_risk_output",
            name="risk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.batch_cvd_risk_risk",
            ),
        ),
        migrations.AddField(
            model_name="cvd_risk_clinician_patient",
            name="clinician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.clinicians"
            ),
        ),
        migrations.AddField(
            model_name="cvd_risk_clinician_patient",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.patients"
            ),
        ),
        migrations.AddField(
            model_name="cvd_risk_patient_outcomes",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.patients"
            ),
        ),
        migrations.AddField(
            model_name="cvd_risk_questionnaire",
            name="admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.admins",
            ),
        ),
        migrations.AddField(
            model_name="cvd_risk_questionnaire",
            name="dependencies",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.cvd_risk_questionnaire",
            ),
        ),
        migrations.AddField(
            model_name="cvd_risk_questionresponseoptions",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.cvd_risk_questionnaire",
            ),
        ),
        migrations.AddField(
            model_name="cvd_risk_responses",
            name="option_selected",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.cvd_risk_questionresponseoptions",
            ),
        ),
        migrations.AddField(
            model_name="cvd_risk_responses",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.patients"
            ),
        ),
        migrations.AddField(
            model_name="cvd_risk_responses",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.cvd_risk_questionnaire",
            ),
        ),
        migrations.AddField(
            model_name="batch_cvd_risk_risk",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.ml_models"
            ),
        ),
        migrations.AddField(
            model_name="batch_cvd_risk_model_features",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.ml_models"
            ),
        ),
        migrations.AddField(
            model_name="risk_stratification",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.patients"
            ),
        ),
        migrations.DeleteModel(
            name="ClinicianPatient",
        ),
        migrations.AlterUniqueTogether(
            name="cvd_risk_clinician_patient",
            unique_together={("clinician", "patient")},
        ),
        migrations.AlterUniqueTogether(
            name="batch_cvd_risk_model_features",
            unique_together={("model", "feature")},
        ),
    ]
