# Generated by Django 5.2 on 2025-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_users_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patients",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
