# Generated by Django 5.2 on 2025-05-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_patients_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvd_risk_questionnaire",
            name="answer_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
