# Generated by Django 5.2 on 2025-05-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_cvd_risk_questionnaire_dependencies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cvd_risk_questionnairedependency",
            old_name="to_question",
            new_name="conditional_question",
        ),
        migrations.RenameField(
            model_name="cvd_risk_questionnairedependency",
            old_name="from_question",
            new_name="triggering_question",
        ),
        migrations.AlterUniqueTogether(
            name="cvd_risk_questionnairedependency",
            unique_together={("triggering_question", "conditional_question")},
        ),
    ]
