# Generated by Django 5.2 on 2025-06-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_risk_stratification_alert_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvd_risk_clinician_patient",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
