# Generated by Django 5.2 on 2025-06-11 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_cvd_risk_clinician_patient_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVD_Risk_Model_InputFeatures",
            fields=[
                ("feature_id", models.AutoField(primary_key=True, serialize=False)),
                ("feature_name", models.CharField(max_length=255)),
                ("feature_description", models.TextField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cvd_risk_questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CVD Risk Model Input Features",
                "db_table": "CVD_Risk_Model_InputFeatures",
                "unique_together": {("question", "feature_name")},
            },
        ),
        migrations.CreateModel(
            name="CVD_Risk_FeatureThresholds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold_type", models.CharField(max_length=20)),
                ("threshold_value", models.FloatField()),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cvd_risk_model_inputfeatures",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CVD Risk Feature Thresholds",
                "db_table": "CVD_Risk_FeatureThresholds",
                "unique_together": {("feature", "threshold_type")},
            },
        ),
        migrations.CreateModel(
            name="CVD_ModelFeatureMappings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.ml_models",
                    ),
                ),
                (
                    "input_feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cvd_risk_model_inputfeatures",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Model Feature Mappings",
                "db_table": "CVD_ModelFeatureMappings",
                "unique_together": {("model", "input_feature")},
            },
        ),
    ]
