# Generated by Django 5.2 on 2025-06-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_cvd_risk_model_inputfeatures_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cvd_risk_featurethresholds",
            unique_together={("feature",)},
        ),
        migrations.RemoveField(
            model_name="cvd_risk_featurethresholds",
            name="threshold_type",
        ),
    ]
