# Generated by Django 4.2.20 on 2025-06-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_clinicianaccessrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicianaccessrequest",
            name="password_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
