# Generated by Django 4.2.20 on 2025-06-26 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_clinicianaccessrequest_password_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="patients",
            name="clinician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.clinicians",
            ),
        ),
    ]
