# Generated by Django 5.2 on 2025-06-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_cvd_risk_featurethresholds_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvd_risk_responses",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
