# Generated by Django 5.2.3 on 2025-06-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_patients_clinician"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cvd_risk_questionresponseoptions",
            old_name="value_range_end",
            new_name="encoded_value",
        ),
        migrations.RenameField(
            model_name="patients",
            old_name="gender",
            new_name="sex",
        ),
        migrations.AlterUniqueTogether(
            name="cvd_risk_clinician_patient",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="cvd_risk_questionresponseoptions",
            name="value_range_start",
        ),
        migrations.AddField(
            model_name="cvd_risk_responses",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cvd_risk_responses",
            name="submission_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="risk_stratification",
            name="submission_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="CVD_Risk_Model_InputFeatures",
            fields=[
                ("feature_id", models.AutoField(primary_key=True, serialize=False)),
                ("feature_name", models.CharField(max_length=255)),
                (
                    "encoded_option",
                    models.ForeignKey(
                        blank=True,
                        help_text="For categorical features: which specific option this feature checks",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.cvd_risk_questionresponseoptions",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cvd_risk_questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CVD Risk Model Input Features",
                "db_table": "CVD_Risk_Model_InputFeatures",
                "unique_together": {("question", "feature_name")},
            },
        ),
        migrations.CreateModel(
            name="CVD_Risk_FeatureThresholds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold_value", models.FloatField()),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cvd_risk_model_inputfeatures",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CVD Risk Feature Thresholds",
                "db_table": "CVD_Risk_FeatureThresholds",
                "unique_together": {("feature",)},
            },
        ),
        migrations.CreateModel(
            name="CVD_Risk_CalculatedFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.ml_models",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.patients",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cvd_risk_model_inputfeatures",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CVD Risk Calculated Features",
                "db_table": "CVD_Risk_CalculatedFeatures",
                "unique_together": {("patient", "model", "feature")},
            },
        ),
        migrations.CreateModel(
            name="CVD_ModelFeatureMappings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.ml_models",
                    ),
                ),
                (
                    "input_feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cvd_risk_model_inputfeatures",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Model Feature Mappings",
                "db_table": "CVD_ModelFeatureMappings",
                "unique_together": {("model", "input_feature")},
            },
        ),
        migrations.CreateModel(
            name="FeatureOptionMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=300)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cvd_risk_questionresponseoptions",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cvd_risk_questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Feature Option Mappings",
                "db_table": "Feature_Option_Mappings",
                "unique_together": {("feature_name", "question")},
            },
        ),
    ]
