# Generated by Django 5.2 on 2025-06-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_cvd_risk_responses_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvd_risk_responses",
            name="submission_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
