# Generated by Django 5.2.3 on 2025-06-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0015_rename_value_range_end_cvd_risk_questionresponseoptions_encoded_value_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinicianaccessrequest",
            options={"verbose_name_plural": "Clinician Access Requests"},
        ),
        migrations.AlterModelTable(
            name="clinicianaccessrequest",
            table="Clinician_Access_Request",
        ),
    ]
