# Generated by Django 5.2 on 2025-06-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_cvd_risk_responses_submission_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVD_Risk_CalculatedFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cvd_risk_model_inputfeatures",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.ml_models",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.patients",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CVD Risk Calculated Features",
                "db_table": "CVD_Risk_CalculatedFeatures",
                "unique_together": {("patient", "model", "feature")},
            },
        ),
    ]
