# Generated by Django 5.2 on 2025-06-12 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_cvd_risk_calculatedfeatures"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvd_risk_calculatedfeatures",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
