# Generated by Django 5.2 on 2025-06-15 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_cvd_risk_calculatedfeatures_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cvd_risk_questionresponseoptions",
            old_name="value_range_end",
            new_name="encoded_value",
        ),
        migrations.RemoveField(
            model_name="cvd_risk_model_inputfeatures",
            name="feature_description",
        ),
        migrations.RemoveField(
            model_name="cvd_risk_questionresponseoptions",
            name="value_range_start",
        ),
        migrations.AddField(
            model_name="cvd_risk_model_inputfeatures",
            name="encoded_option",
            field=models.ForeignKey(
                blank=True,
                help_text="Relevant only for categorical features – single or multi select",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.cvd_risk_questionresponseoptions",
            ),
        ),
    ]
