# Generated by Django 5.2 on 2025-06-15 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            
"0018_rename_value_range_end_cvd_risk_questionresponseoptions_encoded_value_and_more",
        ),
    ]

    operations = [
        # Commented out due to migration error
        # migrations.AlterUniqueTogether(
        #     name="cvd_risk_clinician_patient",
        #     unique_together=set(),
        # ),
        migrations.AlterField(
            model_name="cvd_risk_model_inputfeatures",
            name="encoded_option",
            field=models.ForeignKey(
                blank=True,
                help_text="For categorical features: which specific option this feature checks",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.cvd_risk_questionresponseoptions",
            ),
        ),
    ]

