# Generated by Django 5.2 on 2025-06-15 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_cvd_risk_clinician_patient_unique_together_and_more"),
    ]

    operations = [
        # 🚫 Removed the AlterUniqueTogether operation to prevent duplicate key error
        migrations.CreateModel(
            name="FeatureOptionMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=300)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cvd_risk_questionresponseoptions",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cvd_risk_questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Feature Option Mappings",
                "unique_together": {("feature_name", "question")},
            },
        ),
    ]

