# Generated by Django 5.2 on 2025-06-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_cvd_risk_clinician_patient_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patients",
            old_name="gender",
            new_name="sex",
        ),
        migrations.AlterUniqueTogether(
            name="cvd_risk_clinician_patient",
            unique_together=set(),
        ),
    ]
