# Generated by Django 5.2 on 2025-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_rename_gender_patients_sex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk_stratification",
            name="submission_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
